import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Cpu, Zap, ShieldCheck, Settings, PenTool, LayoutTemplate } from 'lucide-react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Custom Control Panel Manufacturing | Nandini Enterprises',
  description: 'CPRI-certified electrical and automation control panels including PCC, MCC, PLC, VFD, and Synchronization panels.',
};

export default function ControlPanelsPage() {
  return (
    <div className="bg-[#F7F9FC] min-h-screen pt-24 font-sans text-[var(--color-ne-blue-corp)]">
      
      {/* Hero Section */}
      <section className="relative bg-[var(--color-ne-blue-corp)] py-20 lg:py-32 overflow-hidden">
        <div className="absolute inset-0 z-0 opacity-40">
          <Image 
            src="https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=2000&q=80" 
            alt="Control Panels" 
            fill 
            className="object-cover mix-blend-multiply"
            priority
          />
        </div>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="max-w-3xl">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white font-outfit leading-tight mb-6">
              CPRI-Certified <span className="text-blue-400">Control Panel</span> Manufacturing
            </h1>
            <p className="text-lg md:text-xl text-slate-300 leading-relaxed font-mono">
              Engineered for safety, durability, and extreme industrial conditions. We design and manufacture custom PCC, MCC, PLC, VFD, and Synchronization panels for mission-critical applications.
            </p>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-16">
            
            {/* Left Content Column */}
            <div className="lg:col-span-8 font-mono text-slate-700 leading-loose space-y-8">
              
              <h2 className="text-3xl md:text-4xl font-bold text-[var(--color-ne-blue-corp)] font-outfit">
                The Backbone of Industrial Electrical Distribution
              </h2>
              
              <p>
                An industrial control panel is far more than a mere metal enclosure housing switchgear; it is the central nervous system governing power distribution, motor control, and automated logic. A poorly designed panel leads to catastrophic thermal runaways, crippling short circuits, and unscheduled plant shutdowns. Nandini Enterprises operates a state-of-the-art, CPRI-certified panel manufacturing facility dedicated to engineering custom control panels that meet the most stringent safety and performance standards in the industry.
              </p>

              <p>
                With over 18 years of deeply ingrained electrical engineering expertise, we do not utilize off-the-shelf, one-size-fits-all solutions. Our design methodology begins with an exhaustive analysis of your specific plant load, environmental conditions, and future expansion requirements. We utilize advanced CAD software for 3D layout planning, ensuring optimal thermal management, adequate short-circuit withstand capacity, and strict adherence to IP (Ingress Protection) ratings tailored for harsh industrial environments, from dusty cement plants to highly corrosive chemical facilities.
              </p>

              <h3 className="text-2xl md:text-3xl font-bold text-[var(--color-ne-blue-corp)] font-outfit mt-12 mb-6">
                PCC, MCC, and Intelligent Motor Control
              </h3>
              
              <p>
                Our core manufacturing capability includes heavy-duty Power Control Centers (PCC) and Motor Control Centers (MCC). For PCCs, we deploy high-capacity Air Circuit Breakers (ACBs) and intelligently routed aluminum/copper busbars designed to handle massive incomer currents with zero thermal degradation. Our MCCs feature modular, fully draw-out or fixed-type compartments equipped with advanced motor protection relays, ensuring that every pump, fan, and conveyor in your facility is safeguarded against overloads, phase imbalances, and earth faults.
              </p>

              <p>
                As industrial processes become more complex, the demand for intelligent motor control has surged. We manufacture specialized Variable Frequency Drive (VFD) panels and soft starter panels, acting as authorized channel partners for Yaskawa. These panels require meticulous internal layout design to mitigate electromagnetic interference (EMI) and effectively dissipate the significant heat generated by solid-state power electronics, ensuring the longevity of the drives and the stability of the plant grid.
              </p>

              <h3 className="text-2xl md:text-3xl font-bold text-[var(--color-ne-blue-corp)] font-outfit mt-12 mb-6">
                Automation, SCADA, and Synchronization Panels
              </h3>

              <p>
                Beyond power distribution, we are masters of automation logic. We design and build sophisticated PLC (Programmable Logic Controller) and SCADA panels that orchestrate entire manufacturing lines. These panels feature meticulously wired I/O modules, redundant power supplies, and clean-power isolation transformers to ensure digital signals remain entirely uncorrupted by adjacent high-voltage equipment. We ensure every wire is ferruled, every component is tagged, and every circuit is thoroughly documented for effortless future troubleshooting.
              </p>

              <p>
                For facilities requiring uninterrupted power, we engineer DG (Diesel Generator) Synchronization panels and Auto Mains Failure (AMF) panels. These highly critical systems employ advanced microprocessors to seamlessly match voltage, frequency, and phase angles between multiple generator sets and the utility grid. This enables load sharing, peak shaving, and entirely seamless power transitions during grid failures, guaranteeing that your critical industrial processes never experience a blackout.
              </p>

            </div>

            {/* Right Sidebar */}
            <div className="lg:col-span-4 space-y-8">
              
              {/* Capabilities Box */}
              <div className="bg-[#F7F9FC] p-8 rounded-2xl border border-slate-200 shadow-sm">
                <h4 className="text-xl font-bold text-[var(--color-ne-blue-corp)] font-outfit mb-6 border-b border-slate-200 pb-4">
                  Panel Categories
                </h4>
                <ul className="space-y-4 font-mono text-sm text-slate-700">
                  <li className="flex items-start gap-3">
                    <Zap className="w-5 h-5 text-[var(--color-ne-blue-steel)] shrink-0" />
                    <span>Power Control Centers (PCC)</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <Settings className="w-5 h-5 text-[var(--color-ne-blue-steel)] shrink-0" />
                    <span>Motor Control Centers (MCC)</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <Cpu className="w-5 h-5 text-[var(--color-ne-blue-steel)] shrink-0" />
                    <span>PLC & SCADA Automation Panels</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <LayoutTemplate className="w-5 h-5 text-[var(--color-ne-blue-steel)] shrink-0" />
                    <span>VFD & Soft Starter Panels</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <PenTool className="w-5 h-5 text-[var(--color-ne-blue-steel)] shrink-0" />
                    <span>DG Synchronization & AMF Panels</span>
                  </li>
                  <li className="flex items-start gap-3">
                    <ShieldCheck className="w-5 h-5 text-[var(--color-ne-blue-steel)] shrink-0" />
                    <span>APFC (Power Factor) Panels</span>
                  </li>
                </ul>
              </div>

              {/* CTA Box */}
              <div className="bg-gradient-to-br from-[var(--color-ne-blue-corp)] to-[var(--color-ne-blue-steel)] p-8 rounded-2xl text-white shadow-xl">
                <h4 className="text-2xl font-bold font-outfit mb-4">Custom Panel Design</h4>
                <p className="text-slate-300 font-mono text-sm mb-8 leading-relaxed">
                  Provide us with your Single Line Diagram (SLD) or load list, and our engineering team will design a CPRI-certified panel tailored to your exact specifications.
                </p>
                <Link href="/contact" className="flex items-center justify-center gap-2 w-full py-4 bg-[var(--color-ne-blue-steel)] hover:bg-blue-500 rounded-lg font-bold transition-colors">
                  Request a Panel Quote <ArrowRight className="w-4 h-4" />
                </Link>
              </div>

            </div>

          </div>
        </div>
      </section>

    </div>
  );
}
